### ISSUE TITLE
Still Unarming charms by accident

### ISSUE THREAD

**Issue by autobotrevamp** [nobodyrandom/mhAutobot#14]
It will arm and then disarm the charm, but the HUD will still say charm is armed, hence not using any charm but hunting. Charge counter keeps going to 0 because of that...
On old UI, haven't had new UI yet so can't say if problem is the same for new UI
When this problem happens, the HUD says Trap power: <charm name> instead of Charm: <charm name>, so maybe you could use this as a check for whether the charm is armed properly or not.

**Comment by nobodyrandom** [comment]
hmm interesting take, but I think I have found the problem with the bot.
Horn sounding/page loading throws around loads of ajax, and the script originally has things to trap this and know what is going on. What the bot did was find that the page loaded few times and queued arming the charms multiple times.

I will try work out a fix for this, but it will take some time.

One more thing, I am busy on other stuff atm and will not be able to get the fix out as fast as I want to.

**Comment by nobodyrandom** [comment]
(I'll push your idea out as temp fix for now, but it will not work as a perma fix)

**Comment by nobodyrandom** [comment]
Note: this bug does not just affect charm arming, but also affects both trap and base arming. Especially when more than one change of trap setup is required.

**Comment by TheImmortalLS** [comment]
I was using a ghetto fix earlier. Nobodyrandom, what is you change in the last update from 540b to what we have now? My ghetto fix no longer works.

My ghetto fix for the charge egg 2015 worked by using local storage variables to log whether eggstra or eggscavator was armed. it checked to see if a charm was armed by local storage, and if it was, it exited, else, armed, set local storage= armed (true), set other charm (eggstra with eggscavator and vv. to false).


This only works on 540b btw
 
replace checkCharge with this at around line 750
function checkCharge(stopDischargeAt) {
    try {
			var charge = parseInt(document.getElementsByClassName("chargeQuantity")[0].innerText);

			if (charge == 20) {
				setStorage("discharge", true.toString());
				//If Eggstra is not armed, arm it.
					if (getStorage("armedEggstra") == "false"){
						checkThenArm(null, "trinket", "Eggstra");				
						setStorage("armedEggstra",true.toString());
						//Eggstra is armed, thus Eggscavator can't be armed
						setStorage("armedEggscavator", false.toString());  
					}	
			}			
			else if (charge <= stopDischargeAt) {
				setStorage("discharge", false.toString());
					if(getStorage("armedEggscavator") == "false"){
					checkThenArm(null, "trinket", "Eggscavator");				
					setStorage("armedEggscavator", true.toString());
					//Eggscavator is armed, thus Eggstra can't be armed
					setStorage("armedEggstra",false.toString());
					}
			}
			return;
		}
		catch (e) {
        return console.debug(e.message);
    }
}

add these two variables at 2200ish

//charm checking can be done with var charmArmed = getPageVariableForChrome('user.trinket_name'); + indexOf("name") to check if there (!=-1)
	
	//func checkCharge
	var armedEggstra = getStorage("armedEggstra");
    if (armedEggstra == undefined || armedEggstra == null) {
        setStorage("armedEggstra", "false");
    } else if (armedEggstra == true || armedEggstra.toLowerCase() == "true") {
        armedEggstra = true;
    } else {
        armedEggstra = false;
    }
    armedEggstra = undefined;
	
	var armedEggscavator = getStorage("armedEggscavator");
    if (armedEggscavator == undefined || armedEggscavator == null) {
        setStorage("armedEggscavator", "false");
    } else if (armedEggscavator == true || armedEggscavator.toLowerCase() == "true") {
        armedEggscavator = true;
    } else {
        armedEggscavator = false;
    }
    armedEggscavator = undefined;

**Comment by autobotrevamp** [comment]
Not sure what Nobodyrandom added to latest version, but it has caused a new problem:
Script now only tries to arm charm when none is armed, but does not change charm when another charm is already armed.

**Comment by nobodyrandom** [comment]
@TheImmortalLS that fix will only work for one single event and is not the best solution to fixing the problem.

@autobotrevamp The newest version, I've added a temp bypass which checks if charm has been armed through ajax and assume it being armed, therefore no longer needing to be "re"-armed

Which then raises the problem of charm/trap switching not working.

**Comment by nobodyrandom** [comment]
One thing is I am trying to write a code to combat ajax trap switching.

Checking the DOM elements of the page, there is only one bit of it useable, which is the charm armed in the area with all the gold,bait,trap armed etc

Problem with using this is that longer trap/charm names are truncated meaning they use "..." to shorten names. I will try to add a checker on whether currently armed item is what we want and do a rearm if not.

**Comment by nobodyrandom** [comment]
BTW the security hole in prev builds was not in this part of the bot, but in the way the bot fetches data from hornTracker.

**Comment by nobodyrandom** [comment]
OK I have pushed out ver 550b on gitHub, give it a try pls and see how it goes? It should fix

**Comment by nobodyrandom** [comment]
I'll write a trap setup override later on, can I please get a confirmation this bug is (temp) fixed

**Comment by nobodyrandom** [comment]
Did a small fix on the interval counters etc that manages trap arming, now preventing infinite looping if charm/trap is not found in inv.

Pls check ver 558b

**Comment by autobotrevamp** [comment]
On 558b, have still seen it saying trap power: Charmname
After 1 hunt by bot still not arming correct charm.
Upon page refresh bot arms correct charm.

**Comment by nobodyrandom** [comment]
Hmm then the problem is more annoying that it seems, might be something to do with the interval counter.

**Comment by TheImmortalLS** [comment]
I modified the code to do only what I actually needed to do. It is a suboptimal solution, but it is the only thing I am using at the moment. I'm lazy and I use a lazy approach.

**Comment by nobodyrandom** [comment]
Hmm I do not seem to see the error... Using charge egg(17) right now

**Comment by nobodyrandom** [comment]
On build 560/561

**Comment by autobotrevamp** [comment]
Here is the screenshot of the trap arming page where it goes wrong:
http://prntscr.com/6xv6l3

**Comment by nobodyrandom** [comment]
This is not a problem with the bot, but a problem on MH side, where charms list does not load. The bot will then not be able to find the charm.
Please refresh the page in this case.

I'll increase the wait timer for page to load on the next version, but I doubt this problem will be fixed.

**Comment by nobodyrandom** [comment]
Interesting, I think I just fixed that problem... Increasing the time didnt work, but rewriting the waiting code works...

Released fix on ver 566b

**Comment by nobodyrandom** [comment]
Can I get confirmation for fix

**Comment by TheImmortalLS** [comment]
I'll have to check it. Currently on 2.0.1c, but will revert to the revamp+mod

**Comment by nobodyrandom** [comment]
Chrome version is just for people who does not want to install/do not know how to.

For the mod, pls use version B (the enhance + revamp) 1.4.565b

**Comment by TheImmortalLS** [comment]
Anyways, no bugs found. The code works for charms.

**Comment by TheImmortalLS** [comment]
btw how do you add a method to the enhanced version? I'm planning on writing some code for a SB+/dark chocolate/arcane setup, but I do not know how to add the HTML option. I know only Java-Javascript is sort of a stretch for me.

**Comment by nobodyrandom** [comment]
One last check on this issue. Blended (revamp + enhanced) version 2.0.11b SHOULD fix everything.

Even did code to combat ajax, and cause a better trap in the best list to be armed.
